create table salesman(s_no int primary key,s_name varchar(25) not null,place varchar(10),phone varchar(10)unique);
create table salesorder(ordr_no int primary key,ord date not null,s_no int references salesman(s_no),d_type char(1)check(d_type in('p','P','F','f')),order_status varchar(15)check(order_status in('inprocess','fullfilled','backorder','cancelled')));
insert into salesman values(159,'appu','calicut',9523694276);
insert into salesman values(158,'maya','ksargord',9523914942);
insert into salesman values(157,'koya','malapuram',9914728031);
insert into salesman values(156,'jasu','wayanad',9183095421);
insert into salesman values(155,'ziya','ernakulam',959326379);
select * from salesman;
insert into salesorder values(30,'21/3/24',159,'F','cancelled');
insert into salesorder values(34,'9/3/24',158,'P','fullfilled');
insert into salesorder values(38,'23/3/24',157,'f','backorder');
insert into salesorder values(37,'12/3/24',156,'P','inprocess');
insert into salesorder values(36,'15/3/24',155,'F','cancelled');
select * from salesorder;
alter table salesman drop constraint salesman_phone_key;
alter table salesorder drop constraint salesorder_s_no_fkey;
alter table salesorder drop constraint salesorder_d_type_check;
alter table salesman add primary key(s_no);
alter table salesorder add foreign key(s_no)references salesman(s_no);
alter table salesorder add constraint d_type check(d_type in('P','p','F','f'));